# Generated by Django 3.1.6 on 2021-02-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20210218_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingcomment',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posting.posting'),
        ),
    ]
