# Generated by Django 3.1.6 on 2021-02-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0002_auto_20210218_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='like_user',
            field=models.ManyToManyField(related_name='user_like_review', through='product.ReviewLike', to='user.User'),
        ),
    ]
