# Generated by Django 3.1.6 on 2021-02-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210218_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryfee',
            old_name='fee',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='detailcategory',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
